export const GAME_PANEL = {
    NONE: "NONE",
    START_PANEL: "START_PANEL",
    PAUSE_PANEL: "PAUSE_PANEL",
    GAME_OVER_WIN_PANEL: "GAME_OVER_WIN_PANEL",
    GAME_OVER_LOSE_PANEL: "GAME_OVER_LOSE_PANEL",
    WAITING_FOR_GAME_RESPONSE: "WAITING_FOR_GAME_RESPONSE",
    SHARE_PANEL: "SHARE_PANEL",
    ERROR_PANEL: "ERROR_PANEL",
    GAMEPLAY_PANEL: "GAMEPLAY_PANEL",
};